### PR TITLE
Architecture Center contribution for upgrade to Ase V2 to V3

### PR DESCRIPTION
**Pull request by DeeplyDiligent**
This update complements this pull request on the architecture center which updates v2 to v3

https://github.com/MicrosoftDocs/architecture-center-pr/pull/10140

### CODE REVIEW

**Comment by DeeplyDiligent** [comment]
@ckittel sorry for the late reply - we have just finished the High Availability documentation. Please review now

**Review by josevarela — CHANGES_REQUESTED** [review]
The conversion to bicep and new deployment scripts look good to me. Only noticed some inconsistencies in the naming convention in bicep and, in a few cases, not following the bicep recommendations: 

There are a few resource names in Bicep that don't follow best practice recommendations: https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/best-practices#names. In particular the recommendations include using camelCase,  and avoid "name" when defining a resource. I highlighted a couple of examples in-line. 

Please do an end-to-end pass on the naming convention, if possible

**Comment by DeeplyDiligent** [comment]
@josevarela thanks i have made changes requested - i have fixed all symbolic names as you mentioned

cc: @suhasaraos

**Review by josevarela — APPROVED** [review]
Looks good

**Pull request merged**
